#!/bin/fish

set pass $argv[1]
if test -z "$pass"
    echo "Please type your password as the first argument!"
    exit 0
end

echo "You're installing Arch Linux with password '$pass' for both root and dm1nh."

ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
hwclock --systohc

echo "en_US.UTF-8 UTF-8" >/etc/locale.gen
# or use this
# sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf
echo "KEYMAP=us" >/etc/vconsole.conf
echo arch >/etc/hostname
echo "127.0.0.1 localhost\n::1       localhost\n127.0.1.1 arch.localdomain arch" >>/etc/hosts
echo root:$pass | chpasswd

# You can add xorg to the installation packages, I usually add it at the DE or WM install script
pacman -S --noconfirm \
    alsa-utils \
    base-devel \
    bluez \
    bluez-utils \
    bridge-utils \
    btrfs-progs \
    curl \
    dialog \
    dosfstools \
    efibootmgr \
    firewalld \
    fuse3 \
    git \
    grub \
    grub-btrfs \
    inotify-tools \
    jq \
    linux-headers \
    man \
    mtools \
    neovim \
    networkmanager \
    network-manager-applet \
    nfs-utils \
    ntfs-3g \
    openssh \
    os-prober \
    pavucontrol \
    pipewire \
    pipewire-alsa \
    pipewire-pulse \
    pipewire-jack \
    reflector \
    rsync \
    sudo \
    timeshift \
    tree \
    unzip \
    wget \
    wpa_supplicant \
    xdg-utils \
    xdg-user-dirs

grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=Arch #change the directory to /boot/efi is you mounted the EFI partition at /boot/efi
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable sshd
systemctl enable bluetooth.service
systemctl enable fstrim.timer
systemctl enable firewalld

useradd -m dm1nh
echo dm1nh:$pass | chpasswd
usermod -aG wheel dm1nh

echo "dm1nh ALL=(ALL) ALL" >>/etc/sudoers.d/dm1nh

echo "Done. Reboot and enjoy!"
